clean:
	cd median_frames/8.00-9.00
	rm median_frames*.png	
	
	
	
all:
	del *.*
	cd median_frames\9.00-10.00 06.07.2023
	rm *.png
	cd median_frames\10.00-11.00 06.07.2023
	rm *.png
	cd median_frames\11.00-12.00 06.07.2023
	rm *.png

	